### ISSUE TITLE
Transfer of slaughter not robust

### ISSUE THREAD

**Issue by k-r-a-s-s** [allfed/allfed-integrated-model#116]
https://github.com/allfed/allfed-integrated-model/blob/64b0435207f0c85c80f26a6a0297e0f7603c6f07/src/food_system/calculate_animals_and_feed_over_time.py#L457

Will potentially be overwritten as we we overhaul how the animal feed system works, but right now this seems to break if Pig Slaughter >> Pig Population. This is the case in bahrain, at it ends up assigning a neagtive slaughter rate to cows on this line.

Consider not fixing for now, and revisiting after overhaul.

**Comment by morganrivers** [comment]
the way slaughter hours works was totally redone. This is no longer relevant
