### ISSUE TITLE
print(example_food) not working

### ISSUE THREAD

**Issue by k-r-a-s-s** [allfed/allfed-integrated-model#117]
https://github.com/allfed/allfed-integrated-model/blob/4252ee2e8145b7049c4b562b164f5b974eba5436/src/food_system/food.py#L51

I have defined a simple food and the generalised print function fails.

`example_food=Food(10,3,1)`

`print(example_food.fat)`

works as expected, prints "3"

but

`example_food=Food(10,3,1)`

`print(example_food)`

fails with error on line 807 from food.py

`Traceback (most recent call last):
  File "/src/food_system/animal_populations.py", line 223, in <module>
    print(example_food)
  File "src/food_system/food.py", line 807, in __str__
    if self.conversions.include_fat:
AttributeError: 'UnitConversions' object has no attribute 'include_fat'`

**Comment by morganrivers** [comment]
This is a matter of correct usage of the food object. set_nutrition_requirements() must be used.
The thing is, when you have a food it needs to be able to be converted to different units. To do that, you need to know the population of the country/world in question, and whether to include fat or protein in the particular food instance.

You can look at tests/test_food.py to see how to properly initialize a food.
```
"""
Test Suite for the food module.
"""

import pytest
import numpy as np
from src.food_system.food import Food


@pytest.fixture(scope="module", autouse=True)
def set_nutrition_requirements():
    Food.conversions.set_nutrition_requirements(
        kcals_daily=100,
        fat_daily=10,
        protein_daily=10,
        include_fat=True,
        include_protein=True,
        population=1000,
    )


def create_food_monthly(kcals=[1, 2, 1], fat=[1, 2, 2], protein=[1, 2, 2]):
    """
    creates a food instance that has monthly values and returns it
    """
    food_monthly = Food(
        kcals=np.array(kcals),
        fat=np.array(fat),
        protein=np.array(protein),
        kcals_units="kcals each month",
        fat_units="kcals each month",
        protein_units="kcals each month",
    )
    return food_monthly
```

So in practice, usually this has already been called on the Food class, but when removed from the function for testing, the above must be run first.

**Comment by lukaszgajewski** [comment]
This is a symptom of the issue described in #165
