### ISSUE TITLE
Document functions (inputs, outputs, operations)

### ISSUE THREAD

**Issue by morganrivers** [allfed/allfed-integrated-model#12]

**Comment by florianjehn** [comment]
@morganrivers has this happened?

**Comment by morganrivers** [comment]
clearly not

**Comment by florianjehn** [comment]
I must admit this was a bit of an unnecessary question on my part ^^ Was just going through all issues and did not pay much attention to the title.

**Comment by florianjehn** [comment]
Code is now much better documented
