### ISSUE TITLE
conversion values

### ISSUE THREAD

**Issue by morganrivers** [allfed/allfed-integrated-model#15]
A lot of conversion values are spread throughout the constants file, some of them even appearing the same way as the input constants to the model. Keep those kinds of values somewhere else to not confuse them as inputs to the model. not a big deal though, just another thing to try and make it clear what’s input and what’s output (and what’s an intermediate calc ulation)

**Comment by florianjehn** [comment]
I think I will create a new few with functions for conversion, this makes it clearer what is happening and declutters the code in general.
