### ISSUE TITLE
make it more explicit which ultimate constants the constants file is generating

### ISSUE THREAD

**Issue by morganrivers** [allfed/allfed-integrated-model#17]
There actually aren’t that many inputs to the model. The constants function is by contrast rather overwhelming. It would be helpful to make it more explicit which ultimate constants the constants file is generating for the model. A lot of the “constants” are indeed constant, but not necessarily direct inputs to the model.

**Comment by florianjehn** [comment]
Is this referring to the part we talked about on slack? Meaning that this will be moved to a csv file?

**Comment by florianjehn** [comment]
I think this is changed by now @morganrivers ?
