### ISSUE TITLE
get rid of messy stuff with excess calculator function in analysis

### ISSUE THREAD

**Issue by morganrivers** [allfed/allfed-integrated-model#27]

**Comment by florianjehn** [comment]
@morganrivers has this happened?

**Comment by morganrivers** [comment]
no

**Comment by morganrivers** [comment]
analysis has been rewritten a while back. Excess calculation was used to calculate diets... this is only really used in the "    while True:" block in run_model_with_resilient_foods.py.

The messiness was moved to get_increased_excess_to_feed() in interpret_results.

it's not really 'messy' anymore as much as a bit clunky. For example, the months to calculated diet are hard coded.

I'll create a more specific issue now that things have been moved around.
