### ISSUE TITLE
Get fat and protein working in the model

### ISSUE THREAD

**Issue by morganrivers** [allfed/allfed-integrated-model#29]
fix the edge cases with low fat levels or protein when you try to solve the diet and it tends to fail assertions or loop up to 30 and skip over 7.8 (generally, uses excess calories even if there's not enough fat/protein, and that doesn't work with the iteration)

**Comment by florianjehn** [comment]
@morganrivers has this happened?

**Comment by morganrivers** [comment]
not yet.

This will happen generally in the with resilient food diet calculation

**Comment by morganrivers** [comment]
This is a duplicate with #43
