### ISSUE TITLE
deal with edge case feed delay < biofuel delay

### ISSUE THREAD

**Issue by morganrivers** [allfed/allfed-integrated-model#42]

**Comment by florianjehn** [comment]
@morganrivers has this happened?

**Comment by morganrivers** [comment]
no

**Comment by morganrivers** [comment]
I've just run all the tests where long_delayed_shutoff is defined in scenarios.py as being 2 months feed, 4 months biofuel.
Argentina worked for this scenario.  So at least sometimes, this doesn't cause issues.
And then I ran the whole `pytest` and there were no bugs.
Closing.
