### ISSUE TITLE
File referenced by pre-print was deleted; recreate file or edit pre-print to refer to new file

### ISSUE THREAD

**Issue by david-mears-2** [allfed/allfed-integrated-model#46]
[This commit](https://github.com/allfed/allfed-integrated-model/commit/011936411e866267e172de69dd836dc01bc066d5) deletes a file (sensitivity_analysis.py) which is referenced in [the Supplementary Information pdf](https://assets.researchsquare.com/files/rs-1446444/v1/36a70d63f8505435f3738b26.pdf) attached to the preprint

I'm not sure why it was deleted.

Maintaining a link between the preprint and the repo sounds brittle compared to simply citing the values used in the preprint - and easier for readers to follow.

**Comment by florianjehn** [comment]
@morganrivers please make the repository citable using cenodo. This way the paper can reference to a specific version of the model to avoid such issues.

**Comment by florianjehn** [comment]
https://zenodo.org/

**Comment by morganrivers** [comment]
Would it be possible for you to set this up for us?

I think you should have all the relevant files.

I've copied mike who can share all the calculations and spreadsheets that
are relevant.

**Comment by morganrivers** [comment]
I don't know how to give you access. you already have admin on
allfed-integrated-model. I couldn't find any other way to give this to you.

Maybe ask tim who owns the allfed git admin?

I've asked him to give this over to me but he hasn't ever responded to this
request.

**Comment by florianjehn** [comment]
"If your organization's repositories do not show up in the list, please ensure you have enabled [third-party access](https://help.github.com/articles/approving-third-party-applications-for-your-organization/) to the Zenodo application. Private repositories are not supported."

Checked again a bit more and this here seems to be the problem. Maybe you have the rights to enable this? Will also contact Tim

**Comment by florianjehn** [comment]
Is working now and the repository can be cited.
